name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node 14.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: prepare package
        run: mkdir out && mv package.json out && mv dist out && mv LICENSE out
      
      - name: Prepare Master Release
        uses: s0/git-publish-subdir-action@develop
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          REPO: self
          BRANCH: master-dist
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"